frameworkDir = framework

objs += $(outtmp)/controller.o \
		$(outtmp)/server.o \
		$(outtmp)/servletrequest.o \
		$(outtmp)/servletrequestmgr.o \
		$(outtmp)/controllerparam.o \
		$(outtmp)/httproutermanager.o \
		$(outtmp)/httproutermap.o \
		$(outtmp)/httpresourcemanager.o \
		$(outtmp)/httpresponseentity.o \
		$(outtmp)/httprouter.o \
		$(outtmp)/htmltemplate.o \
		$(outtmp)/htmltemplatetextitem.o \
		$(outtmp)/htmltemplateobjectitem.o \
		$(outtmp)/htmltemplateconditionitem.o \
		$(outtmp)/htmltemplatereferitem.o \
		$(outtmp)/htmltemplaterangeitem.o \
		$(outtmp)/htmltemplateincludeitem.o \
		$(outtmp)/htmltemplatedefineitem.o \
		$(outtmp)/htmltemplatelenitem.o \
		$(outtmp)/htmltemplateindexitem.o \
		$(outtmp)/htmltemplatewithitem.o \
		$(outtmp)/htmltemplatefunctionitem.o \
		$(outtmp)/templatedotcmdparser.o \
		$(outtmp)/templateconditioncmdparser.o  \
		$(outtmp)/templaterefercmdparser.o  \
		$(outtmp)/templaterangecmdparser.o  \
		$(outtmp)/templateincludecmdparser.o  \
		$(outtmp)/templatedefinecmdparser.o  \
		$(outtmp)/templatelencmdparser.o  \
		$(outtmp)/templateindexcmdparser.o \
		$(outtmp)/templatewithcmdparser.o \
		$(outtmp)/templatefunctioncmdparser.o \
		$(outtmp)/mqcenter.o \
		$(outtmp)/mqmessage.o \
		$(outtmp)/mqconnection.o \
		$(outtmp)/mqcenterbuilder.o \
		$(outtmp)/mqundeliveredcomponent.o


$(outtmp)/httproutermanager.o :$(frameworkDir)/HttpRouterManager.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/HttpRouterManager.cpp -o $(outtmp)/httproutermanager.o

$(outtmp)/httproutermap.o :$(frameworkDir)/HttpRouterMap.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/HttpRouterMap.cpp -o $(outtmp)/httproutermap.o

$(outtmp)/httpresourcemanager.o :$(frameworkDir)/HttpResourceManager.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/HttpResourceManager.cpp -o $(outtmp)/httpresourcemanager.o

$(outtmp)/httpresponseentity.o :$(frameworkDir)/HttpResponseEntity.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/HttpResponseEntity.cpp -o $(outtmp)/httpresponseentity.o

$(outtmp)/httprouter.o :$(frameworkDir)/HttpRouter.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/HttpRouter.cpp -o $(outtmp)/httprouter.o

$(outtmp)/controller.o :$(frameworkDir)/Controller.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/Controller.cpp -o $(outtmp)/controller.o

$(outtmp)/controllerparam.o :$(frameworkDir)/ControllerParam.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/ControllerParam.cpp -o $(outtmp)/controllerparam.o

$(outtmp)/server.o :$(frameworkDir)/Server.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/Server.cpp -o $(outtmp)/server.o

$(outtmp)/servletrequest.o :$(frameworkDir)/ServletRequest.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/ServletRequest.cpp -o $(outtmp)/servletrequest.o

$(outtmp)/servletrequestmgr.o :$(frameworkDir)/ServletRequestManager.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/ServletRequestManager.cpp -o $(outtmp)/servletrequestmgr.o

$(outtmp)/htmltemplate.o :$(frameworkDir)/template/HtmlTemplate.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplate.cpp -o $(outtmp)/htmltemplate.o

$(outtmp)/htmltemplatetextitem.o :$(frameworkDir)/template/HtmlTemplateTextItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateTextItem.cpp -o $(outtmp)/htmltemplatetextitem.o

$(outtmp)/htmltemplateconditionitem.o :$(frameworkDir)/template/HtmlTemplateConditionItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateConditionItem.cpp -o $(outtmp)/htmltemplateconditionitem.o

$(outtmp)/htmltemplatereferitem.o :$(frameworkDir)/template/HtmlTemplateReferItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateReferItem.cpp -o $(outtmp)/htmltemplatereferitem.o

$(outtmp)/htmltemplaterangeitem.o :$(frameworkDir)/template/HtmlTemplateRangeItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateRangeItem.cpp -o $(outtmp)/htmltemplaterangeitem.o

$(outtmp)/htmltemplateincludeitem.o :$(frameworkDir)/template/HtmlTemplateIncludeItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateIncludeItem.cpp -o $(outtmp)/htmltemplateincludeitem.o

$(outtmp)/htmltemplatedefineitem.o :$(frameworkDir)/template/HtmlTemplateDefineItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateDefineItem.cpp -o $(outtmp)/htmltemplatedefineitem.o

$(outtmp)/htmltemplatelenitem.o :$(frameworkDir)/template/HtmlTemplateLenItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateLenItem.cpp -o $(outtmp)/htmltemplatelenitem.o

$(outtmp)/htmltemplateindexitem.o :$(frameworkDir)/template/HtmlTemplateIndexItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateIndexItem.cpp -o $(outtmp)/htmltemplateindexitem.o

$(outtmp)/htmltemplatewithitem.o :$(frameworkDir)/template/HtmlTemplateWithItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateWithItem.cpp -o $(outtmp)/htmltemplatewithitem.o

$(outtmp)/htmltemplatefunctionitem.o :$(frameworkDir)/template/HtmlTemplateFunctionItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateFunctionItem.cpp -o $(outtmp)/htmltemplatefunctionitem.o

$(outtmp)/htmltemplateobjectitem.o :$(frameworkDir)/template/HtmlTemplateObjectItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/HtmlTemplateObjectItem.cpp -o $(outtmp)/htmltemplateobjectitem.o

$(outtmp)/templatedotcmdparser.o :$(frameworkDir)/template/TemplateDotCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateDotCmdParser.cpp -o $(outtmp)/templatedotcmdparser.o

$(outtmp)/templateconditioncmdparser.o :$(frameworkDir)/template/TemplateConditionCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateConditionCmdParser.cpp -o $(outtmp)/templateconditioncmdparser.o

$(outtmp)/templaterefercmdparser.o :$(frameworkDir)/template/TemplateReferCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateReferCmdParser.cpp -o $(outtmp)/templaterefercmdparser.o

$(outtmp)/templaterangecmdparser.o :$(frameworkDir)/template/TemplateRangeCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateRangeCmdParser.cpp -o $(outtmp)/templaterangecmdparser.o

$(outtmp)/templateincludecmdparser.o :$(frameworkDir)/template/TemplateIncludeCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateIncludeCmdParser.cpp -o $(outtmp)/templateincludecmdparser.o

$(outtmp)/templatedefinecmdparser.o :$(frameworkDir)/template/TemplateDefineCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateDefineCmdParser.cpp -o $(outtmp)/templatedefinecmdparser.o

$(outtmp)/templatelencmdparser.o :$(frameworkDir)/template/TemplateLenCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateLenCmdParser.cpp -o $(outtmp)/templatelencmdparser.o

$(outtmp)/templateindexcmdparser.o :$(frameworkDir)/template/TemplateIndexCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateIndexCmdParser.cpp -o $(outtmp)/templateindexcmdparser.o

$(outtmp)/templatewithcmdparser.o :$(frameworkDir)/template/TemplateWithCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateWithCmdParser.cpp -o $(outtmp)/templatewithcmdparser.o

$(outtmp)/templatefunctioncmdparser.o :$(frameworkDir)/template/TemplateFunctionCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/template/TemplateFunctionCmdParser.cpp -o $(outtmp)/templatefunctioncmdparser.o

$(outtmp)/mqcenter.o :$(frameworkDir)/mq/MqCenter.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/mq/MqCenter.cpp -o $(outtmp)/mqcenter.o

$(outtmp)/mqcenterbuilder.o :$(frameworkDir)/mq/MqCenterBuilder.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/mq/MqCenterBuilder.cpp -o $(outtmp)/mqcenterbuilder.o

$(outtmp)/mqundeliveredcomponent.o :$(frameworkDir)/mq/MqUndeliveredComponent.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/mq/MqUndeliveredComponent.cpp -o $(outtmp)/mqundeliveredcomponent.o

$(outtmp)/mqmessage.o :$(frameworkDir)/mq/MqMessage.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/mq/MqMessage.cpp -o $(outtmp)/mqmessage.o

$(outtmp)/mqconnection.o :$(frameworkDir)/mq/MqConnection.cpp
	$(cppcompiler) $(gagiracppflags) -c $(frameworkDir)/mq/MqConnection.cpp -o $(outtmp)/mqconnection.o
