archiveDir = ./framework/distribution/archive

objs += $(outtmp)/archivecenter.o \
		$(outtmp)/archivemessage.o \
		$(outtmp)/archiveoption.o \
		$(outtmp)/archiveconnection.o \
		$(outtmp)/archivehandlerresult.o \
		$(outtmp)/archivefile.o \
		$(outtmp)/archiveinputstream.o \
		$(outtmp)/archiveoutputstream.o \
		$(outtmp)/archivefilemanager.o \
		$(outtmp)/archiveclient.o 

#$(outtmp)/archivelinker.o :$(archiveDir)/ArchiveLinker.cpp
#	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveLinker.cpp -o $(outtmp)/archivelinker.o

$(outtmp)/archivecenter.o :$(archiveDir)/ArchiveCenter.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveCenter.cpp -o $(outtmp)/archivecenter.o

$(outtmp)/archivemessage.o :$(archiveDir)/ArchiveMessage.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveMessage.cpp -o $(outtmp)/archivemessage.o

$(outtmp)/archiveoption.o :$(archiveDir)/ArchiveOption.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveOption.cpp -o $(outtmp)/archiveoption.o

$(outtmp)/archiveconnection.o :$(archiveDir)/ArchiveConnection.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveConnection.cpp -o $(outtmp)/archiveconnection.o

$(outtmp)/archivehandlerresult.o :$(archiveDir)/ArchiveHandleResult.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveHandleResult.cpp -o $(outtmp)/archivehandlerresult.o

$(outtmp)/archivefile.o :$(archiveDir)/ArchiveFile.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveFile.cpp -o $(outtmp)/archivefile.o

$(outtmp)/archiveinputstream.o :$(archiveDir)/ArchiveInputStream.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveInputStream.cpp -o $(outtmp)/archiveinputstream.o

$(outtmp)/archiveoutputstream.o :$(archiveDir)/ArchiveOutputStream.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveOutputStream.cpp -o $(outtmp)/archiveoutputstream.o

$(outtmp)/archivefilemanager.o :$(archiveDir)/ArchiveFileManager.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveFileManager.cpp -o $(outtmp)/archivefilemanager.o

$(outtmp)/archiveclient.o :$(archiveDir)/ArchiveClient.cpp
	$(cppcompiler) $(gagiracppflags) -c $(archiveDir)/ArchiveClient.cpp -o $(outtmp)/archiveclient.o
