templateDir = ./framework/template

objs += $(outtmp)/htmltemplate.o \
		$(outtmp)/htmltemplatetextitem.o \
		$(outtmp)/htmltemplateobjectitem.o \
		$(outtmp)/htmltemplateconditionitem.o \
		$(outtmp)/htmltemplatereferitem.o \
		$(outtmp)/htmltemplaterangeitem.o \
		$(outtmp)/htmltemplateincludeitem.o \
		$(outtmp)/htmltemplatedefineitem.o \
		$(outtmp)/htmltemplatelenitem.o \
		$(outtmp)/htmltemplateindexitem.o \
		$(outtmp)/htmltemplatewithitem.o \
		$(outtmp)/htmltemplatefunctionitem.o \
		$(outtmp)/templatedotcmdparser.o \
		$(outtmp)/templateconditioncmdparser.o  \
		$(outtmp)/templaterefercmdparser.o  \
		$(outtmp)/templaterangecmdparser.o  \
		$(outtmp)/templateincludecmdparser.o  \
		$(outtmp)/templatedefinecmdparser.o  \
		$(outtmp)/templatelencmdparser.o  \
		$(outtmp)/templateindexcmdparser.o \
		$(outtmp)/templatewithcmdparser.o \
		$(outtmp)/templatefunctioncmdparser.o 


$(outtmp)/htmltemplate.o :$(templateDir)/HtmlTemplate.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplate.cpp -o $(outtmp)/htmltemplate.o

$(outtmp)/htmltemplatetextitem.o :$(templateDir)/HtmlTemplateTextItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateTextItem.cpp -o $(outtmp)/htmltemplatetextitem.o

$(outtmp)/htmltemplateconditionitem.o :$(templateDir)/HtmlTemplateConditionItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateConditionItem.cpp -o $(outtmp)/htmltemplateconditionitem.o

$(outtmp)/htmltemplatereferitem.o :$(templateDir)/HtmlTemplateReferItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateReferItem.cpp -o $(outtmp)/htmltemplatereferitem.o

$(outtmp)/htmltemplaterangeitem.o :$(templateDir)/HtmlTemplateRangeItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateRangeItem.cpp -o $(outtmp)/htmltemplaterangeitem.o

$(outtmp)/htmltemplateincludeitem.o :$(templateDir)/HtmlTemplateIncludeItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateIncludeItem.cpp -o $(outtmp)/htmltemplateincludeitem.o

$(outtmp)/htmltemplatedefineitem.o :$(templateDir)/HtmlTemplateDefineItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateDefineItem.cpp -o $(outtmp)/htmltemplatedefineitem.o

$(outtmp)/htmltemplatelenitem.o :$(templateDir)/HtmlTemplateLenItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateLenItem.cpp -o $(outtmp)/htmltemplatelenitem.o

$(outtmp)/htmltemplateindexitem.o :$(templateDir)/HtmlTemplateIndexItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateIndexItem.cpp -o $(outtmp)/htmltemplateindexitem.o

$(outtmp)/htmltemplatewithitem.o :$(templateDir)/HtmlTemplateWithItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateWithItem.cpp -o $(outtmp)/htmltemplatewithitem.o

$(outtmp)/htmltemplatefunctionitem.o :$(templateDir)/HtmlTemplateFunctionItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateFunctionItem.cpp -o $(outtmp)/htmltemplatefunctionitem.o

$(outtmp)/htmltemplateobjectitem.o :$(templateDir)/HtmlTemplateObjectItem.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/HtmlTemplateObjectItem.cpp -o $(outtmp)/htmltemplateobjectitem.o

$(outtmp)/templatedotcmdparser.o :$(templateDir)/TemplateDotCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateDotCmdParser.cpp -o $(outtmp)/templatedotcmdparser.o

$(outtmp)/templateconditioncmdparser.o :$(templateDir)/TemplateConditionCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateConditionCmdParser.cpp -o $(outtmp)/templateconditioncmdparser.o

$(outtmp)/templaterefercmdparser.o :$(templateDir)/TemplateReferCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateReferCmdParser.cpp -o $(outtmp)/templaterefercmdparser.o

$(outtmp)/templaterangecmdparser.o :$(templateDir)/TemplateRangeCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateRangeCmdParser.cpp -o $(outtmp)/templaterangecmdparser.o

$(outtmp)/templateincludecmdparser.o :$(templateDir)/TemplateIncludeCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateIncludeCmdParser.cpp -o $(outtmp)/templateincludecmdparser.o

$(outtmp)/templatedefinecmdparser.o :$(templateDir)/TemplateDefineCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateDefineCmdParser.cpp -o $(outtmp)/templatedefinecmdparser.o

$(outtmp)/templatelencmdparser.o :$(templateDir)/TemplateLenCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateLenCmdParser.cpp -o $(outtmp)/templatelencmdparser.o

$(outtmp)/templateindexcmdparser.o :$(templateDir)/TemplateIndexCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateIndexCmdParser.cpp -o $(outtmp)/templateindexcmdparser.o

$(outtmp)/templatewithcmdparser.o :$(templateDir)/TemplateWithCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateWithCmdParser.cpp -o $(outtmp)/templatewithcmdparser.o

$(outtmp)/templatefunctioncmdparser.o :$(templateDir)/TemplateFunctionCmdParser.cpp
	$(cppcompiler) $(gagiracppflags) -c $(templateDir)/TemplateFunctionCmdParser.cpp -o $(outtmp)/templatefunctioncmdparser.o